package knowledge

import (
	"fmt"
	"sort"
	"strings"
)

type Evidence struct {
	ID             string
	SourceID       string
	DocumentID     string
	Title          string
	ParentPath     string
	Content        string
	ContentHash    string
	SourceType     string
	SourceKey      string
	SourceVersion  string
	AuthorityLevel int
	Score          float64
}

type ContextSelection struct {
	Evidence      []Evidence
	Rendered      string
	TokenCount    int
	Excluded      map[string]string
	PolicyVersion string
}

// BuildContext applies a total token budget, exact-hash deduplication, and a
// per-document diversity cap. Evidence identifiers are generated by the
// builder, so a model cannot introduce arbitrary source identifiers.
func BuildContext(candidates []Evidence, tokenBudget, perDocumentLimit int) ContextSelection {
	if tokenBudget <= 0 {
		tokenBudget = 4000
	}
	if perDocumentLimit <= 0 {
		perDocumentLimit = 3
	}
	sort.SliceStable(candidates, func(i, j int) bool {
		if candidates[i].AuthorityLevel != candidates[j].AuthorityLevel {
			return candidates[i].AuthorityLevel > candidates[j].AuthorityLevel
		}
		return candidates[i].Score > candidates[j].Score
	})
	selection := ContextSelection{Excluded: map[string]string{}, PolicyVersion: "authority-diversity-budget-v1"}
	seenHash := map[string]bool{}
	documentCount := map[string]int{}
	var rendered strings.Builder
	for _, candidate := range candidates {
		originalID := candidate.ID
		if seenHash[candidate.ContentHash] {
			selection.Excluded[candidate.ID] = "duplicate_content_hash"
			continue
		}
		if documentCount[candidate.DocumentID] >= perDocumentLimit {
			selection.Excluded[candidate.ID] = "per_document_diversity_limit"
			continue
		}
		tokens := EstimateTokens(candidate.Content)
		if selection.TokenCount+tokens > tokenBudget {
			selection.Excluded[candidate.ID] = "context_token_budget"
			continue
		}
		if candidate.SourceID == "" {
			candidate.SourceID = originalID
		}
		candidate.ID = fmt.Sprintf("K-%03d", len(selection.Evidence)+1)
		selection.Evidence = append(selection.Evidence, candidate)
		selection.TokenCount += tokens
		seenHash[candidate.ContentHash] = true
		documentCount[candidate.DocumentID]++
		fmt.Fprintf(&rendered, "\n<EVIDENCE id=%q authority=%q source=%q version=%q hash=%q section=%q>\n%s\n</EVIDENCE>\n",
			candidate.ID, authorityLabel(candidate.AuthorityLevel), candidate.SourceType+":"+candidate.SourceKey,
			candidate.SourceVersion, candidate.ContentHash, candidate.ParentPath, candidate.Content)
	}
	selection.Rendered = rendered.String()
	return selection
}

func authorityLabel(level int) string {
	switch {
	case level >= 100:
		return "AUTHORITATIVE"
	case level >= 90:
		return "APPROVED"
	case level >= 70:
		return "VERIFIED"
	case level >= 40:
		return "HISTORICAL"
	case level > 0:
		return "INFERRED"
	default:
		return "UNTRUSTED"
	}
}
