CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(128) COLLATE "C" PRIMARY KEY,
    applied_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflows (
    id UUID PRIMARY KEY,
    gitlab_project_id BIGINT NOT NULL,
    issue_iid BIGINT NOT NULL,
    issue_title VARCHAR(512) NOT NULL,
    state VARCHAR(64) COLLATE "C" NOT NULL,
    source_hash CHAR(64) COLLATE "C" NOT NULL DEFAULT '',
    revision INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_workflow_issue UNIQUE (gitlab_project_id, issue_iid)
);

CREATE INDEX IF NOT EXISTS idx_workflow_state ON workflows (state, updated_at);

CREATE TABLE IF NOT EXISTS source_snapshots (
    id UUID PRIMARY KEY,
    workflow_id UUID NOT NULL REFERENCES workflows(id),
    confluence_page_id VARCHAR(64) COLLATE "C" NOT NULL,
    source_version INTEGER NOT NULL,
    title VARCHAR(512) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    source_updated_at VARCHAR(64) NOT NULL DEFAULT '',
    content_hash CHAR(64) COLLATE "C" NOT NULL,
    normalized_text TEXT NOT NULL,
    raw_storage TEXT NOT NULL,
    images_json JSONB NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_snapshot_version UNIQUE (workflow_id, confluence_page_id, source_version, content_hash)
);

CREATE INDEX IF NOT EXISTS idx_snapshot_workflow ON source_snapshots (workflow_id, created_at);

CREATE TABLE IF NOT EXISTS artifacts (
    id UUID PRIMARY KEY,
    workflow_id UUID NOT NULL REFERENCES workflows(id),
    artifact_type VARCHAR(64) COLLATE "C" NOT NULL,
    artifact_version INTEGER NOT NULL,
    source_hash CHAR(64) COLLATE "C" NOT NULL,
    content_json JSONB NOT NULL,
    markdown TEXT NOT NULL,
    model VARCHAR(128) NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    generated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_artifact_version UNIQUE (workflow_id, artifact_type, artifact_version)
);

CREATE INDEX IF NOT EXISTS idx_artifact_latest ON artifacts (workflow_id, artifact_type, generated_at);

CREATE TABLE IF NOT EXISTS gates (
    id UUID PRIMARY KEY,
    workflow_id UUID NOT NULL REFERENCES workflows(id),
    gate_type VARCHAR(32) COLLATE "C" NOT NULL,
    status VARCHAR(32) COLLATE "C" NOT NULL,
    artifact_id UUID NOT NULL REFERENCES artifacts(id),
    revision INTEGER NOT NULL,
    reviewer_ids JSONB NOT NULL,
    opened_at TIMESTAMPTZ(6) NOT NULL,
    decided_at TIMESTAMPTZ(6),
    decision_actor BIGINT NOT NULL DEFAULT 0,
    feedback TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gate_workflow_status ON gates (workflow_id, status, gate_type);

CREATE TABLE IF NOT EXISTS gate_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gate_id UUID NOT NULL REFERENCES gates(id),
    action VARCHAR(32) COLLATE "C" NOT NULL,
    actor_id BIGINT NOT NULL,
    actor_username VARCHAR(255) NOT NULL,
    feedback TEXT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_gate_actor_action UNIQUE (gate_id, actor_id, action)
);

CREATE TABLE IF NOT EXISTS event_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key VARCHAR(255) COLLATE "C" NOT NULL,
    event_type VARCHAR(96) COLLATE "C" NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(24) COLLATE "C" NOT NULL DEFAULT 'READY',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by VARCHAR(255) NOT NULL DEFAULT '',
    lease_until TIMESTAMPTZ(6),
    last_error TEXT NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ(6),
    CONSTRAINT uq_event_dedupe UNIQUE (dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_event_claim ON event_queue (status, available_at, id);
CREATE INDEX IF NOT EXISTS idx_event_lease ON event_queue (status, lease_until);

CREATE TABLE IF NOT EXISTS outbox_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key VARCHAR(255) COLLATE "C" NOT NULL,
    message_type VARCHAR(96) COLLATE "C" NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(24) COLLATE "C" NOT NULL DEFAULT 'READY',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by VARCHAR(255) NOT NULL DEFAULT '',
    lease_until TIMESTAMPTZ(6),
    last_error TEXT NOT NULL,
    external_id VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ(6),
    CONSTRAINT uq_outbox_dedupe UNIQUE (dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_outbox_claim ON outbox_messages (status, available_at, id);
CREATE INDEX IF NOT EXISTS idx_outbox_lease ON outbox_messages (status, lease_until);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id UUID NOT NULL REFERENCES workflows(id),
    event_type VARCHAR(96) COLLATE "C" NOT NULL,
    actor_id BIGINT NOT NULL DEFAULT 0,
    details_json JSONB NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_workflow ON audit_events (workflow_id, created_at);
