ALTER TABLE context_entries ADD COLUMN IF NOT EXISTS required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS provider_model_id VARCHAR(255) COLLATE "C" NOT NULL DEFAULT '';

ALTER TABLE evaluation_outputs ADD COLUMN IF NOT EXISTS provider_response_id VARCHAR(255) COLLATE "C" NOT NULL DEFAULT '';
ALTER TABLE evaluation_outputs ADD COLUMN IF NOT EXISTS provider_model_id VARCHAR(255) COLLATE "C" NOT NULL DEFAULT '';
ALTER TABLE evaluation_outputs ADD COLUMN IF NOT EXISTS input_tokens BIGINT NOT NULL DEFAULT 0;
ALTER TABLE evaluation_outputs ADD COLUMN IF NOT EXISTS output_tokens BIGINT NOT NULL DEFAULT 0;
